### PR TITLE
readme: use "Boolean" rather than "bool" in type signatures

### PR DESCRIPTION
**Pull request by davidchambers**
It seems to me the name of the type should be capitalized, and should be `Boolean` rather than `Bool` to match the name of the constructor.

### CODE REVIEW

**Comment by svozza** [comment]
Thanks David, could you do me a favour before I merge this and bump the version number in `package.json` ? We automatically release to NPM on every merge to master and it won't work if the version numbers aren't incremented.

**Comment by davidchambers** [comment]
I've updated `"version"` in **package.json**. This is an unusual release process, I must say! :)

**Comment by svozza** [comment]
Yes, somewhat unorthodox but we're big fans of continuous delivery. We'll look at automating this soon.

**Comment by cullophid** [comment]
Thanks for the pull request :)

**Pull request merged**
