### PR TITLE
Support for getDay

### LINKED ISSUE #38: Support for get('day')
Hi, thanks for this awesome lib. I use it in my current project happily.

I find out there is no `get('Day')` currently which supports to get a weekday from a Date instance, like what [`Date.prototype.getDay`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date/getDay) does.

I am not sure it is a good idea to add this feature to this lib. If it looks good to you, I would like to create a PR for it.

### PR DESCRIPTION
**Pull request by wuct**
Close #38

### CODE REVIEW

**Comment by lulalachen** [comment]
You can update doc as well :)

**Comment by wuct** [comment]
@lulalachen done

**Comment by lulalachen** [comment]
@wuct should npm versions be updated as well?

**Comment by svozza** [comment]
Yes, you'll need to bump the version to `4.3`.

**Comment by wuct** [comment]
@svozza @lulalachen sure

**Comment by cullophid** [comment]
@wuct  Thank you very much!
@svozza if you are also satisfied then ill merge

**Comment by svozza** [comment]
Yep, all good from my side.

**Comment by cullophid** [comment]
Thank you very much @wuct

**Comment by wuct** [comment]
@cullophid Thanks for merging

**Pull request merged**
