### PR TITLE
Remove build folder from source control

### PR DESCRIPTION
**Pull request by TheLudd**
The folder aldready existed in gitignore but the files had probably been
added for tracking earlier.

### CODE REVIEW

**Comment by TheLudd** [comment]
Could do that but IMO it would be better if babel could create the folder. Is it possible?

**Comment by TheLudd** [comment]
Also, is it possible to add empty directories to git?

**Comment by TheLudd** [comment]
Sorry. The issue was that browserify does not do this and they do not seem to intend to change it. https://github.com/substack/node-browserify/issues/402

Would it be ok if I included `mkdir -p dist` in `buildBrowser`? That makes the build a bit tied to linux for now.

**Comment by cullophid** [comment]
I dont have an issue with that. im on a mac.

**Comment by TheLudd** [comment]
Good, fixed. When this is merged I have another PR ready for the other stuff.

**Comment by cullophid** [comment]
Ah you need to manually update the package version otherwise npm gets mad :)

**Pull request merged**
